from datetime import datetime
from typing import Dict, Optional


class InvoiceGenerator:
    """Generate invoices for rental transactions"""
    
    def __init__(self, data_store):
        self.data_store = data_store
    
    def generate(self, user_id: str, property_id: str, invoice_type: str = "rental", 
                 date: str = None, output_format: str = "markdown") -> str:
        """Generate an invoice"""
        property_data = self.data_store.get_property(property_id)
        
        if not property_data:
            return "Error: Property not found"
        
        invoice_date = date or datetime.now().strftime('%Y-%m-%d')
        invoice_number = self._generate_invoice_number()
        
        if invoice_type == "rental":
            return self._generate_rental_invoice(
                user_id, property_data, invoice_number, invoice_date
            )
        elif invoice_type == "management":
            return self._generate_management_invoice(
                user_id, property_data, invoice_number, invoice_date
            )
        else:
            return self._generate_generic_invoice(
                user_id, property_data, invoice_number, invoice_date, invoice_type
            )
    
    def _generate_invoice_number(self) -> str:
        """Generate unique invoice number"""
        return f"INV-{datetime.now().strftime('%Y%m%d')}-{datetime.now().strftime('%H%M%S')}"
    
    def _generate_rental_invoice(self, user_id: str, property_data: Dict, 
                                  invoice_number: str, invoice_date: str) -> str:
        """Generate rental invoice"""
        income = self.data_store.get_income(user_id, property_id=property_data['id'])
        
        total = sum(i['amount'] for i in income)
        
        invoice = f"""# INVOICE

**Invoice Number:** {invoice_number}  
**Date:** {invoice_date}  
**Type:** Rental Income

---

## Property Details

- **Name:** {property_data.get('name', 'N/A')}
- **Address:** {property_data.get('address', 'N/A')}
- **Type:** {property_data.get('property_type', 'residential')}

---

## Rental Income Summary

| Date | Description | Amount |
|------|-------------|--------|
"""
        for i in income:
            invoice += f"| {i.get('date', '')} | {i.get('source', 'Rental')} | £{i['amount']:,.2f} |\n"
        
        invoice += f"""
---

**Total Amount:** £{total:,.2f}

---

## Payment Details

Payment should be made to your designated account.

---

*Generated by TaxPrep - UK Property Tax Assistant*
"""
        
        self.data_store.save_invoice(user_id, property_data['id'], 'rental', 
                                      invoice_date, total, invoice)
        
        return invoice
    
    def _generate_management_invoice(self, user_id: str, property_data: Dict,
                                     invoice_number: str, invoice_date: str) -> str:
        """Generate property management fee invoice"""
        expenses = self.data_store.get_expenses(user_id, property_id=property_data['id'])
        
        management_fees = [e for e in expenses if e.get('category') == 'agent_fees']
        total = sum(e['amount'] for e in management_fees)
        
        invoice = f"""# INVOICE

**Invoice Number:** {invoice_number}  
**Date:** {invoice_date}  
**Type:** Management Fees

---

## Property Details

- **Name:** {property_data.get('name', 'N/A')}
- **Address:** {property_data.get('address', 'N/A')}

---

## Management Fees

"""
        for fee in management_fees:
            invoice += f"- {fee.get('description', 'Management Fee')}: £{fee['amount']:,.2f}\n"
        
        invoice += f"""
---

**Total:** £{total:,.2f}

---

*Generated by TaxPrep*
"""
        
        self.data_store.save_invoice(user_id, property_data['id'], 'management',
                                      invoice_date, total, invoice)
        
        return invoice
    
    def _generate_generic_invoice(self, user_id: str, property_data: Dict,
                                  invoice_number: str, invoice_date: str,
                                  invoice_type: str) -> str:
        """Generate generic invoice"""
        invoice = f"""# INVOICE

**Invoice Number:** {invoice_number}  
**Date:** {invoice_date}  
**Type:** {invoice_type.title()}

---

## Property: {property_data.get('name', 'N/A')}

---

**Type:** {invoice_type.title()} Invoice

---

*Generated by TaxPrep*
"""
        
        self.data_store.save_invoice(user_id, property_data['id'], invoice_type,
                                      invoice_date, 0, invoice)
        
        return invoice
    
    def get_invoices(self, user_id: str, property_id: str = None) -> list:
        """Get all invoices for a user/property"""
        return self.data_store.get_invoices(user_id, property_id)
    
    def export_to_pdf(self, invoice_content: str, output_path: str) -> bool:
        """Export invoice to PDF (placeholder)"""
        print(f"PDF export requires additional dependencies")
        print(f"Would save to: {output_path}")
        return False
    
    def export_to_csv(self, user_id: str, output_path: str) -> bool:
        """Export all invoices to CSV"""
        invoices = self.data_store.get_invoices(user_id)
        
        if not invoices:
            return False
        
        csv_content = "Invoice ID,Property ID,Type,Date,Amount,Created At\n"
        for inv in invoices:
            csv_content += f"{inv['id']},{inv['property_id']},{inv['invoice_type']},{inv['date']},{inv['amount']},{inv['created_at']}\n"
        
        with open(output_path, 'w') as f:
            f.write(csv_content)
        
        return True