from typing import Dict
from datetime import datetime


class ReportGenerator:
    """Generate HMRC-compliant tax reports"""
    
    def __init__(self, data_store):
        self.data_store = data_store
    
    def generate_report(self, user_id: str, tax_year: str = "2025-26", format: str = "markdown") -> str:
        """Generate a comprehensive tax report"""
        from taxprep.tax_calculator import TaxCalculator
        
        calc = TaxCalculator(self.data_store)
        
        properties = self.data_store.get_properties(user_id)
        income = self.data_store.get_income(user_id, tax_year=tax_year)
        expenses = self.data_store.get_expenses(user_id, tax_year=tax_year)
        calc_result = calc.calculate_tax_liability(user_id, tax_year)
        expense_summary = calc.calculate_expense_deductions(user_id, tax_year)
        mtd_status = calc.check_mtd_compliance(user_id)
        
        report = self._generate_markdown(
            user_id, tax_year, properties, income, expenses,
            calc_result, expense_summary, mtd_status
        )
        
        self.data_store.save_report(user_id, tax_year, format, report)
        
        return report
    
    def _generate_markdown(self, user_id, tax_year, properties, income, expenses, calc_result, expense_summary, mtd_status) -> str:
        """Generate markdown report"""
        year_label = tax_year.replace('-', '/')
        
        report = f"""# Property Tax Report - {year_label}

**Generated:** {datetime.now().strftime('%d %B %Y')}  
**User ID:** {user_id}

---

## Executive Summary

| Metric | Amount |
|--------|--------|
| Total Properties | {len(properties)} |
| Total Income | £{calc_result['total_income']:,.2f} |
| Total Expenses | £{calc_result['total_expenses']:,.2f} |
| Net Profit | £{calc_result['net_profit']:,.2f} |
| **Estimated Tax** | **£{calc_result['total_tax']:,.2f}** |

---

## Property Details

"""
        for prop in properties:
            prop_income = sum(i['amount'] for i in income if i.get('property_id') == prop['id'])
            prop_expenses = sum(e['amount'] for e in expenses if e.get('property_id') == prop['id'])
            report += f"""### {prop['name']}

- **Address:** {prop.get('address', 'N/A')}
- **Type:** {prop.get('property_type', 'residential')}
- **Income:** £{prop_income:,.2f}
- **Expenses:** £{prop_expenses:,.2f}
- **Net:** £{prop_income - prop_expenses:,.2f}

"""

        report += """## Income Breakdown

| Date | Property | Source | Amount |
|------|----------|--------|--------|
"""
        for i in income:
            prop = next((p for p in properties if p['id'] == i.get('property_id')), {})
            prop_name = prop.get('name', 'Unknown') if prop else 'Unknown'
            report += f"| {i.get('date', '')} | {prop_name} | {i.get('source', '')} | £{i['amount']:,.2f} |\n"
        
        report += """
## Expense Breakdown

| Date | Description | Category | Amount |
|------|-------------|----------|--------|
"""
        for e in expenses:
            report += f"| {e.get('date', '')} | {e.get('description', '')} | {e.get('category', '')} | £{e['amount']:,.2f} |\n"
        
        report += f"""
## Tax Calculation

### Allowable Deductions
- Allowable Expenses: £{expense_summary['allowable']:,.2f}
- Disallowed: £{expense_summary['disallowed']:,.2f}

### Estimated Tax Liability
- Income Tax: £{calc_result['income_tax']:,.2f}
- National Insurance: £{calc_result['national_insurance']:,.2f}
- **Total:** £{calc_result['total_tax']:,.2f}

**Effective Tax Rate:** {calc_result['effective_rate']*100:.1f}%

---

## MTD Compliance Status

- **Annual Income:** £{mtd_status['annual_income']:,.2f}
- **MTD Status:** {mtd_status['mtds_status']}
- **Requirement:** {mtd_status['requirement']}

"""
        
        if mtd_status.get('action_required'):
            report += "### Action Required\n"
            for action in mtd_status['action_required']:
                report += f"- {action}\n"
        
        report += """
---

## Important Notes

1. **This is an estimate only** - Verify all figures with a qualified accountant before submission
2. **HMRC deadlines:** Self Assessment returns must be filed by 31 January following the tax year
3. **Record keeping:** Keep all receipts and supporting documents for at least 6 years
4. **MTD:** If your rental income exceeds £50,000, you MUST register for MTD

---

*Generated by TaxPrep - UK Property Tax Assistant*
"""
        
        return report
    
    def generate_sa100_summary(self, user_id: str, tax_year: str = "2025-26") -> Dict:
        """Generate SA100-compatible summary"""
        calc = TaxCalculator(self.data_store)
        result = calc.calculate_tax_liability(user_id, tax_year)
        
        return {
            "tax_year": tax_year,
            "total_income": result['total_income'],
            "total_expenses": result['total_expenses'],
            "net_profit": result['net_profit'],
            "income_tax": result['income_tax'],
            "total_tax": result['total_tax']
        }
    
    def generate_sa105_details(self, user_id: str, tax_year: str = "2025-26") -> Dict:
        """Generate SA105 (Property Income) details"""
        income = self.data_store.get_income(user_id, tax_year=tax_year)
        expenses = self.data_store.get_expenses(user_id, tax_year=tax_year)
        
        return {
            "tax_year": tax_year,
            "total_rental_income": sum(i['amount'] for i in income),
            "total_expenses": sum(e['amount'] for e in expenses),
            "net_profit": sum(i['amount'] for i in income) - sum(e['amount'] for e in expenses),
            "properties": self.data_store.get_properties(user_id)
        }


from taxprep.tax_calculator import TaxCalculator